PassionProject_N01457602/Models/Pet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace PassionProject_N01457602.Models
{
    public class Pet
    {
        //This class describes a pet entity.
        //It is used for actually generating a database table
        [Key]
        public int PetID { get; set; }

        public string PetName { get; set; }

        public string PetColour { get; set; }

        public string PetAge { get; set; }

        public string PetBreed { get; set; }

        public int PetHeight { get; set; }

        public string PetLocation { get; set; }
        

        //A player plays for one team
        [ForeignKey("Customer")]
        public int CustomerID { get; set; }
        public virtual Customer Customer { get; set; }
    }

    //This class can be used to transfer information about a player.
    //also known as a "Data Transfer Object"
    //https://docs.microsoft.com/en-us/aspnet/web-api/overview/data/using-web-api-with-entity-framework/part-5
    //You can think of this class as the 'Model' that was used in 5101.
    //It is simply a vessel of communication
    public class PetDto
    {
        public int PetID { get; set; }
        [DisplayName("Name")]
        public string PetName { get; set; }
        [DisplayName("Colour")]
        public string PetColour { get; set; }
        [DisplayName("Age")]
        public string PetAge { get; set; }
        [DisplayName("Breed")]
        public string PetBreed { get; set; }
        [DisplayName("Height")]
        public int PetHeight { get; set; }
        [DisplayName("Location")]
        public string PetLocation { get; set; }
        
        [DisplayName("Customer ID ")]
        public int CustomerID { get; set; }
    }
}

PassionProject_N01457602/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using PassionProject_N01457602.Models;
using PassionProject_N01457602.Models.ViewModels;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Diagnostics;
using System.Web.Script.Serialization;

namespace PassionProject_N01457602.Controllers
{
    public class CustomerController : Controller
    {

        //Http Client is the proper way to connect to a webapi
        //https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0

        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;


        static CustomerController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false
            };
            client = new HttpClient(handler);
            //change this to match your own local port number
            client.BaseAddress = new Uri("https://localhost:44339/api/");
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));
            //client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", ACCESS_TOKEN);
        }



        // GET: Customer/List
        public ActionResult List()
        {
            string url = "CustomerData/GetCustomers";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<CustomerDto> SelectedCustomers = response.Content.ReadAsAsync<IEnumerable<CustomerDto>>().Result;
                return View(SelectedCustomers);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        
        // GET: Customer/Details/5
        public ActionResult Details(int id)
        {
            ShowCustomer ViewModel = new ShowCustomer();
            
            string url = "customerdata/findcustomer/" + id ;
            HttpResponseMessage response = client.GetAsync(url).Result;
            
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                Debug.WriteLine("hello");
                //Put data into Customer data transfer object
                CustomerDto SelectedCustomer = response.Content.ReadAsAsync<CustomerDto>().Result;
                ViewModel.customer = SelectedCustomer;
                
                return View(ViewModel);
            }

            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Create(Customer CustomerInfo)
        {
            Debug.WriteLine(CustomerInfo.CustomerName);
            string url = "Customerdata/addCustomer";
            Debug.WriteLine(jss.Serialize(CustomerInfo));
            HttpContent content = new StringContent(jss.Serialize(CustomerInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {

                int Customerid = response.Content.ReadAsAsync<int>().Result;
                return RedirectToAction("Details", new { id = Customerid });
            }
            else
            {
                return RedirectToAction("Error");
            }


        }



        public ActionResult Edit(int id)
        {
            string url = "Customerdata/findcustomer/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                //Put data into Customer  data transfer object
                CustomerDto SelectedCustomer = response.Content.ReadAsAsync<CustomerDto>().Result;
                return View(SelectedCustomer);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // POST: Customer/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Edit(int id, Customer CustomerInfo)
        {
            Debug.WriteLine(CustomerInfo.CustomerName);
            string url = "Customerdata/updatecustomer/" + id;
            Debug.WriteLine(jss.Serialize(CustomerInfo));
            HttpContent content = new StringContent(jss.Serialize(CustomerInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Details", new { id = id });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Customer/Delete/5
        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            string url = "customerdata/findcustomer/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                //Put data into Customer data transfer object
                CustomerDto SelectedCustomer = response.Content.ReadAsAsync<CustomerDto>().Result;
                return View(SelectedCustomer);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // POST: Customer/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Delete(int id)
        {
            string url = "customerdata/deletecustomer/" + id;
            //post body is empty
            HttpContent content = new StringContent("");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {

                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        public ActionResult Error()
        {
            return View();
        }
    }
}

PassionProject_N01457602/Controllers/PetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using PassionProject_N01457602.Models;
using PassionProject_N01457602.Models.ViewModels;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Diagnostics;
using System.Web.Script.Serialization;


namespace PassionProject_N01457602.Controllers
{
    public class PetController : Controller
    {
        //Http Client is the proper way to connect to a webapi
        //https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0

        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;


        static PetController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false
            };
            client = new HttpClient(handler);
            //change this to match your own local port number
            client.BaseAddress = new Uri("https://localhost:44339/api/");
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));
            //client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", ACCESS_TOKEN);
        }



        // GET: Pet/List
        public ActionResult List()
        {
            string url = "petdata/getpets";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<PetDto> SelectedPets = response.Content.ReadAsAsync<IEnumerable<PetDto>>().Result;
                return View(SelectedPets);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Pet/Details/5
        public ActionResult Details(int id)
        {
            ShowPet ViewModel = new ShowPet();
            string url = "petdata/findpet/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                //Put data into pet data transfer object
                PetDto SelectedPet = response.Content.ReadAsAsync<PetDto>().Result;
                ViewModel.pet = SelectedPet;


                url = "petdata/findcustomerforpet/" + id;
                response = client.GetAsync(url).Result;
                CustomerDto SelectedCustomer = response.Content.ReadAsAsync<CustomerDto>().Result;
                ViewModel.customer = SelectedCustomer;

                return View(ViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }


        // GET: Pet/Create
        public ActionResult Create()
        {

            return View();
        }



        // POST: Pet/Create
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Create(Pet PetInfo)
        {
            Debug.WriteLine(PetInfo.PetName);
            string url = "petdata/addpet";
            Debug.WriteLine(jss.Serialize(PetInfo));
            HttpContent content = new StringContent(jss.Serialize(PetInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {

                int petid = response.Content.ReadAsAsync<int>().Result;
                return RedirectToAction("Details", new { id = petid });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }


         // GET: Pet/Edit/5
        public ActionResult Edit(int id)
        {
            string url = "petdata/findpet/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                //Put data into Customer data transfer object
                PetDto SelectedPet = response.Content.ReadAsAsync<PetDto>().Result;
                return View(SelectedPet);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }


        // POST: Pet/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Edit(int id, Pet PetInfo)
        {
            Debug.WriteLine(PetInfo.PetName);
            string url = "petdata/updatepet/" + id;
            Debug.WriteLine(jss.Serialize(PetInfo));
            HttpContent content = new StringContent(jss.Serialize(PetInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            { 

                response = client.PostAsync(url, content).Result;

                return RedirectToAction("Details", new { id = id });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Pet/Delete/5
        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            string url = "petdata/findpet/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {
                //Put data into pet data transfer object
                PetDto SelectedPet = response.Content.ReadAsAsync<PetDto>().Result;
                return View(SelectedPet);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // POST: Pet/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Delete(int id)
        {
            string url = "petdata/deletepet/" + id;
            //post body is empty
            HttpContent content = new StringContent("");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            //Can catch the status code (200 OK, 301 REDIRECT), etc.
            //Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {

                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        public ActionResult Error()
        {
            return View();
        }
    }

}

PassionProject_N01457602/Views/Pet/Create.cshtml
@model PassionProject_N01457602.Models.PetDto

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Pet</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.PetName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PetName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PetName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PetColour, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PetColour, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PetColour, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PetAge, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PetAge, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PetAge, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PetBreed, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PetBreed, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PetBreed, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PetHeight, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PetHeight, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PetHeight, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PetLocation, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PetLocation, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PetLocation, "", new { @class = "text-danger" })
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.CustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CustomerID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

PassionProject_N01457602/Views/Pet/DeleteConfirm.cshtml
@model PassionProject_N01457602.Models.PetDto

@{
    ViewBag.Title = "DeleteConfirm";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pet</h4>
    <hr />
    <dl class="dl-horizontal">
        
        <dt>
            @Html.DisplayNameFor(model => model.PetName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PetColour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetColour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PetAge)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetAge)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PetBreed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetBreed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PetHeight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetHeight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PetLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetLocation)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Pet", new { id = Model.PetID }))
    {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "List")
        </div>
    }
</div>

PassionProject_N01457602/Views/Pet/Details.cshtml
@model PassionProject_N01457602.Models.ViewModels.ShowPet

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <div>@Html.ActionLink("Delete", "DeleteConfirm", new { id = Model.pet.PetID })</div>
    <hr />
    <dl class="dl-horizontal">


        <dt>
            @Html.DisplayNameFor(model => model.pet.PetName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pet.PetName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pet.PetColour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pet.PetColour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pet.PetAge)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pet.PetAge)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pet.PetBreed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pet.PetBreed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pet.PetHeight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pet.PetHeight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pet.PetLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pet.PetLocation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.customer.CustomerName)
        </dt>
        <dd>
            @Html.ActionLink(Model.customer.CustomerName, "Details", "Customer", new { id = Model.customer.CustomerID }, new { })
           
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.pet.PetID }) |
    @Html.ActionLink("Back to List", "List")
</p>

PassionProject_N01457602/Views/Pet/Edit.cshtml
@model PassionProject_N01457602.Models.PetDto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pet</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PetID)

        <div class="form-group">
            @Html.LabelFor(model => model.PetName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PetName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PetName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PetColour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PetColour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PetColour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PetAge, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PetAge, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PetAge, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PetBreed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PetBreed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PetBreed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PetHeight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PetHeight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PetHeight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PetLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PetLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PetLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PassionProject_N01457602/Views/Pet/List.cshtml
@model IEnumerable<PassionProject_N01457602.Models.PetDto>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PetName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PetColour)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PetAge)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PetBreed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PetHeight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PetLocation)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PetName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PetColour)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PetAge)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PetBreed)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PetHeight)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PetLocation)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PetID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PetID }) |
            @Html.ActionLink("Delete", "DeleteConfirm", new { id=item.PetID })
        </td>
    </tr>
}

</table>